### ISSUE TITLE
Promo video script & coordination

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-tasks#7]
- Development of video story board highlighting the problem addressed by IMPACT OSS and how it works
- Management of video production
  - ADDED: Development of creative brief for production company
- possibly creation of graphic elements?

**Comment by tmfrnz** [comment]
@ashbowe please add a specification for the demo video here - then it should be straight forward to submit a joint proposal

**Comment by ashbowe** [comment]
Proposed IMPACT OSS promotional video specification

**Purpose**
To develop an animated representation of the problem addressed by IMPACT OSS and how the application works. 

**Audience**
Primary audience: United Nations member States
Secondary audiences: NHRIs, civil society, potential development partners

**Key Messages**

1. States have wide-ranging overlapping obligations (human rights and SDGs)
2. Dealing with these obligations individually can be overwhelming and is inefficient - it often leads to ad hoc reporting and no coordinated approach to implementation
3. Civil society are often disengaged from the process 
4. Siloed approach = No IMPACT. Integrated management and planning of actions = IMPACT
5. IMPACT OSS is **not** a solution in itself. It is a tool to be used by National Mechanisms for Implementation, Reporting and Follow-Up
6. IMPACT OSS features:
- An easy-to-build national implementation plan for all human rights and SDG obligations that eliminates duplication of  activities and reporting and identifies data gaps at the outset of reporting periods;
- Sophisticated clustering of human rights recommendations and SDG targets;
- Automated email reminders for data, direct to the data owners
- Additional automated safeguards against non-entry of data
- Tools to encourage greater coordination and involvement with civil society and to allow for greater oversight and accountability
7. Impact:
- Up to date and more accurate reporting
- Improved data collection
- Easy identification of implementation gaps
- **Greater enjoyment of human rights and achievement of SDGs**
8. IMPACT OSS is open source and freely available. 
9. How to get involved (as a State, NHRI, civil society or potential partner)

Additional message, which can be incorporated into main video for Small States fora:

10. Small States are disproportionately affected by human rights obligations and SDGs. IMPACT OSS a tool to level the playing field

**Draft Storyboard Framework**
1. Animated depiction of people working in silos with human rights obligations and the SDGs being worked on by more than one person or not at all and with civil society disengaged. 
2. The establishment of a NMIRF brings the people depicted into scene one around the same table, as the first step in solving the problem but who still face data collection issues
3. The introduction of IMPACT and a visual depiction of how the information flows into the NMIRF through the application.
4. What happens when people don't enter the data? The safeguards in action merging into the final scene where everything is running smoothly (including showing civil society, NHRI, stats, judiciary, etc. ) involvement. 
5. After a fade out of the story a final frame showing how it can be used, information on the IMPACT OSS group and contact details 

**Requirements**
Video length: 2-4 minutes
Format: MPEG4
Output: High Definition
Language: English, Arabic, Chinese, French, Russian, Spanish (English as a priority if additional languages are problematic) 

**Production Company**
[We Can Make ](http://www.wecanmake.co.uk/), recommended by Universal Rights Group who are funding the video and have previously worked with this production company.

**Comment by tmfrnz** [comment]
#### Description of Services Required

A promotional video is required to showcase the purpose and functionality of IMPACT OSS. Universal Rights Group has pledged the funds required for the production of a promotional video using the company We Can Make (www.wecanmake.co.uk). Management of the video production is required and project proposals are hereby invited.

**Comment by tmfrnz** [comment]
Proposal by Ash (@ashbowe) and Unfold Data (@tmfrnz, @dmprk)
[Uploading Demo video proposal.pdf...]

**Comment by tmfrnz** [comment]
see https://docs.google.com/document/d/1FRg-r-DscVzXB3JOp_m8joDNMv0e8W6Z9qLSBHGEk4I/edit

**Comment by tmfrnz** [comment]
From the URG/Singapore proposal
https://docs.google.com/document/d/1Ti3QxdUeJjcdFzVq96WwzpSf8rQXFlhz8polaEp-xDg/edit?usp=sharing

> **Promotional Video**
> The Group will direct and oversee the production of a 60-90 second promotional video, including provision of visual elements, covering;
> - The difficulties faced by States in receiving large amounts of overlapping recommendations;
> - What IMPACT OSS does to address those problems;
> - A brief overview of the key features;
> - Contact information for the IMPACT OSS Group 
>
> The Group’s activities include:
> - Consultation with the production company;
> - Development of creative brief;
> - Development of story board ideas;
> - Management of video production;
> - Provision of visual elements;
> - Direction in use of colours and visual elements
>
> Not covered by this proposal is the cost of the external production company.
